[package]
name = "landscape-ebpf"
version.workspace = true
edition.workspace = true

[dependencies]
landscape-common = { path = "../landscape-common" }

thiserror = { workspace = true }
libbpf-rs = { workspace = true }
libbpf-sys = { workspace = true }
clap = { workspace = true }
libc = { workspace = true }
ctrlc = { workspace = true }
pnet = { workspace = true }
once_cell = { workspace = true }
# self_cell = { workspace = true }
tokio = { workspace = true, features = ["full"] }
nix = { workspace = true, features = ["net", "user", "sched"] }

socket2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
plain = "0.2"

# logs
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }

etherparse = { workspace = true }
zerocopy = { workspace = true, features = ["derive", "simd"] }

[build-dependencies]
libbpf-cargo = { workspace = true }
vmlinux = { git = "https://github.com/libbpf/vmlinux.h.git", rev = "83a228cf37fc65f2d14e4896a04922b5ee531a94" }

[features]
default = ["libbpf-sys/vendored"]
# # autoconf automake libtool pkg-config m4 make cmake clang llvm autopoint gawk
# apt-get install musl-tools musl-dev libargp-dev
static = ["libbpf-sys/vendored"]
